complete:
  enable_engines: ["google"]

network:
  timeout: 3s

result:
  score:
    scorer: "weight" # use rule scorer.
    weight: # weight map for weight scorer.
      "imdb": 10
      "google": 8
      "bing_videos": 8
    metadata_fields: ["engine", "title", "content", "$QUERY"] # enable metadata fields, used for rule scorer.
    rules:
      - name: "engine_weight_imdb" # rule name.
        score: 100 # score if match this rule.
        enable: true # enable this rule
        conditions: # A rule is matched only when all conditions are matched.
          - field: "engine"
            operator: "in"
            values : ["imdb"]
      - name: "match_query"
        score: 5
        enable: true
        conditions:
          - field: "title"
            operator: "containAny"
            values: ["$QUERY"]

  limits:
    first:  # only for the first page of result
      - imdb: 1 # Maximum of imdb results to be shown



